// Automatically generated by api/generator/api.gen.go, DO NOT EDIT manually
// Package api implements Register method for fiber
package api

import (
	"encoding/json"

	"github.com/gofiber/fiber/v2"
	"github.com/kodmain/thetiptop/api/internal/api/status"
	"github.com/kodmain/thetiptop/api/internal/api/user"
	"github.com/swaggo/swag"
)

func init() {
	json.Unmarshal([]byte(doc), Mapping)
}

// API represents a collection of HTTP endpoints grouped by namespace and version.
var (
	Endpoints map[string]fiber.Handler = map[string]func(*fiber.Ctx) error{
		"status.HealthCheck": status.HealthCheck,
		"status.IP":          status.IP,
		"user.Auth":          user.Auth,
		"user.Register":      user.Register,
	}
	Mapping = &Swagger{}
	doc, _  = swag.ReadDoc()
)
