architecture-beta
    service laptop(akar-icons:laptop-device)[LAPTOP]
    service desktop(akar-icons:desktop-device)[DESKTOP]
    
    group gh(skill-icons:github-dark)[Github]
        service git(skill-icons:git-dark)[Git] in gh
        service gha(skill-icons:githubactions-dark)[Github Actions] in gh
    
    group aws(skill-icons:aws-dark)[AWS]
        service route53(logos:aws-route53)[Route53] in aws
        service cloudfront(logos:aws-cloudfront)[Cloud Front] in aws
        service loadbalancer(logos:aws-elb)[Elastic Load Balancing] in aws
        
        group vpc(logos:aws-vpc)[VPC] in aws
            group public[PUBLIC] in vpc
                group autoscaling(skill-icons:autoscaling-dark)[Auto Scaling Group] in public
                    service server1(logos:aws-ec2)[EC2] in autoscaling
                    service server2(logos:aws-ec2)[EC2] in autoscaling
                    service server3(logos:aws-ec2)[EC2] in autoscaling
                    service server4(logos:aws-ec2)[EC2] in autoscaling

            group private[PRIVATE] in vpc
                service database(logos:aws-rds)[Database] in private

    junction junctionDevices

    junctionDevices:T -- B:laptop
    junctionDevices:L -- T:desktop
    junctionDevices:R --> L:git

    git:R -- L:gha
    gha:R -- L:route53

    cloudfront:L -- R:route53
    loadbalancer:L -- R:cloudfront


    junction junctionLeft
    junction junctionRight

    loadbalancer:R -- L:junctionLeft
    server1:B -- T:junctionLeft
    server2:T -- B:junctionLeft
    junctionLeft:R -- L:junctionRight
    server3:B -- T:junctionRight
    server4:T -- B:junctionRight
    junctionRight:R -- L:database
