include $(CURDIR)/../../lib/default.mk

###########################
#╔═══════════════════════╗#
#║ DOCUMENTATION ACTIONS ║#
#╚════════════════=══════╝#
###########################

project: ## Display project documentation
	glow $(GWD)/project/README.md

deploy: ## Display deploy documentation
	glow $(GWD)/deploy/README.md