//go:build ignore

package main

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"regexp"
	"strings"
)

const (
	header = `
// Automatically generated by api/generator/api.gen.go, DO NOT EDIT manually
// Package api implements Register method for fiber
package api

import (
	"encoding/json"

	"github.com/gofiber/fiber/v2"
	"github.com/swaggo/swag"
)

func init() {
	json.Unmarshal([]byte(doc), Mapping)
}

// API represents a collection of HTTP endpoints grouped by namespace and version.
var (
	Endpoints map[string]fiber.Handler = map[string]func(*fiber.Ctx) error{
`
	footer = `
	}
	Mapping = &docs.Swagger{}
	doc, _  = swag.ReadDoc()
)
`
)

// getGitRoot retourne le chemin du dossier racine du dépôt Git.
// Returns:
// - path: string Chemin du dossier racine Git.
// - err: error Erreur, le cas échéant.
func GetGitRoot() (string, error) {
	cmd := exec.Command("git", "rev-parse", "--show-toplevel")
	output, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(output)), nil
}

func panicOrNotPanic(err error) {
	if err != nil {
		panic(err)
	}
}

func getIds(wd string) []string {
	var ids []string
	re := regexp.MustCompile(`// @Id\s+([^=>\n]+(?:\s*=>\s*[^=>\n]+)*)`)

	err := filepath.Walk(wd, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if shouldScanFile(path, info) {
			fileIds, err := extractIdsFromFilePath(path, re)
			if err != nil {
				return err
			}
			ids = append(ids, fileIds...)
		}
		return nil
	})

	panicOrNotPanic(err)

	return ids
}

func shouldScanFile(path string, info os.FileInfo) bool {
	return !info.IsDir() && !strings.Contains(path, "vendor") && strings.HasSuffix(path, ".go")
}

func extractIdsFromFilePath(path string, re *regexp.Regexp) ([]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	var ids []string
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		matches := re.FindStringSubmatch(scanner.Text())
		if len(matches) > 1 {
			for _, match := range matches[1:] {
				for _, split := range strings.Split(match, "=>") {
					ids = append(ids, strings.TrimSpace(split))
				}
			}
		}
	}

	return ids, nil
}

func main() {
	goimportsPath, err := exec.LookPath("goimports")
	if err != nil {
		panic("goimports not found. Please install it using 'go install golang.org/x/tools/cmd/goimports@latest'")
	}

	wd, err := GetGitRoot()
	panicOrNotPanic(err)

	generatedPath := path.Join(wd, "api/internal/api/api.gen.go")

	err = os.RemoveAll(generatedPath)
	panicOrNotPanic(err)
	file, err := os.Create(generatedPath)
	panicOrNotPanic(err)
	_, err = file.WriteString(header)
	panicOrNotPanic(err)

	uniqueIds := make(map[string]struct{})
	for _, id := range getIds(wd) {
		uniqueIds[id] = struct{}{}
	}

	for id := range uniqueIds {
		_, err = file.WriteString(fmt.Sprintf("\"%s\": %s,\n", id, id))
		panicOrNotPanic(err)
	}

	_, err = file.WriteString(footer)
	panicOrNotPanic(err)

	cmd := exec.Command(goimportsPath, "-w", generatedPath)
	if err := cmd.Run(); err != nil {
		panic(fmt.Sprintf("goimports failed: %s", err))
	}
}
